export const gtfsRouteTypes: Record<
  number,
  { name: string; description?: string }
> = {
  0: {
    name: 'Tram',
    description:
      'Tram, Streetcar, Light rail. Any light rail or street level system within a metropolitan area.',
  },
  1: {
    name: 'Subway',
    description:
      'Subway, Metro. Any underground rail system within a metropolitan area.',
  },
  2: {
    name: 'Rail',
    description: 'Rail. Used for intercity or long-distance travel.',
  },
  3: {
    name: 'Bus',
    description: 'Bus. Used for short- and long-distance bus routes.',
  },
  4: {
    name: 'Ferry',
    description: 'Ferry. Used for short- and long-distance boat service.',
  },
  5: {
    name: 'Cable tram',
    description:
      'Cable tram. Used for street-level rail cars where the cable runs beneath the vehicle, e.g., cable car in San Francisco.',
  },
  6: {
    name: 'Aerial lift',
    description:
      'Aerial lift, suspended cable car (e.g., gondola lift, aerial tramway). Cable transport where cabins, cars, gondolas or open chairs are suspended by means of one or more cables.',
  },
  7: {
    name: 'Funicular',
    description: 'Funicular. Any rail system designed for steep inclines.',
  },
  11: {
    name: 'Trolleybus',
    description:
      'Trolleybus. Electric buses that draw power from overhead wires using poles.',
  },
  12: {
    name: 'Monorail',
    description:
      'Monorail. Railway in which the track consists of a single rail or a beam.',
  },
  100: { name: 'Railway Service' },
  101: { name: 'High Speed Rail Service' },
  102: { name: 'Long Distance Trains' },
  103: { name: 'Inter Regional Rail Service' },
  104: { name: 'Car Transport Rail Service' },
  105: { name: 'Sleeper Rail Service' },
  106: { name: 'Regional Rail Service' },
  107: { name: 'Tourist Railway Service' },
  108: { name: 'Rail Shuttle (Within Complex)' },
  109: { name: 'Suburban Railway' },
  110: { name: 'Replacement Rail Service' },
  111: { name: 'Special Rail Service' },
  112: { name: 'Lorry Transport Rail Service' },
  113: { name: 'All Rail Services' },
  114: { name: 'Cross-Country Rail Service' },
  115: { name: 'Vehicle Transport Rail Service' },
  116: { name: 'Rack and Pinion Railway' },
  117: { name: 'Additional Rail Service' },
  200: { name: 'Coach Service' },
  201: { name: 'International Coach Service' },
  202: { name: 'National Coach Service' },
  203: { name: 'Shuttle Coach Service' },
  204: { name: 'Regional Coach Service' },
  205: { name: 'Special Coach Service' },
  206: { name: 'Sightseeing Coach Service' },
  207: { name: 'Tourist Coach Service' },
  208: { name: 'Commuter Coach Service' },
  209: { name: 'All Coach Services' },
  400: { name: 'Urban Railway Service' },
  401: { name: 'Metro Service' },
  402: { name: 'Underground Service' },
  403: { name: 'Urban Railway Service' },
  404: { name: 'All Urban Railway Services' },
  405: { name: 'Monorail' },
  700: { name: 'Bus Service' },
  701: { name: 'Regional Bus Service' },
  702: { name: 'Express Bus Service' },
  703: { name: 'Stopping Bus Service' },
  704: { name: 'Local Bus Service' },
  705: { name: 'Night Bus Service' },
  706: { name: 'Post Bus Service' },
  707: { name: 'Special Needs Bus' },
  708: { name: 'Mobility Bus Service' },
  709: { name: 'Mobility Bus for Registered Disabled' },
  710: { name: 'Sightseeing Bus' },
  711: { name: 'Shuttle Bus' },
  712: { name: 'School Bus' },
  713: { name: 'School and Public Service Bus' },
  714: { name: 'Rail Replacement Bus Service' },
  715: { name: 'Demand and Response Bus Service' },
  716: { name: 'All Bus Services' },
  800: { name: 'Trolleybus Service' },
  900: { name: 'Tram Service' },
  901: { name: 'City Tram Service' },
  902: { name: 'Local Tram Service' },
  903: { name: 'Regional Tram Service' },
  904: { name: 'Sightseeing Tram Service' },
  905: { name: 'Shuttle Tram Service' },
  906: { name: 'All Tram Services' },
  1000: { name: 'Water Transport Service' },
  1100: { name: 'Air Service' },
  1200: { name: 'Ferry Service' },
  1300: { name: 'Aerial Lift Service' },
  1301: { name: 'Telecabin Service' },
  1302: { name: 'Cable Car Service' },
  1303: { name: 'Elevator Service' },
  1304: { name: 'Chair Lift Service' },
  1305: { name: 'Drag Lift Service' },
  1306: { name: 'Small Telecabin Service' },
  1307: { name: 'All Telecabin Services' },
  1400: { name: 'Funicular Service' },
  1500: { name: 'Taxi Service' },
  1501: { name: 'Communal Taxi Service' },
  1502: { name: 'Water Taxi Service' },
  1503: { name: 'Rail Taxi Service' },
  1504: { name: 'Bike Taxi Service' },
  1505: { name: 'Licensed Taxi Service' },
  1506: { name: 'Private Hire Service Vehicle' },
  1507: { name: 'All Taxi Services' },
  1700: { name: 'Miscellaneous Service' },
  1702: { name: 'Horse-drawn Carriage' },
} satisfies Record<string, { name: string; description?: string }>
