// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
import { ChakraProviders } from './chakra'
import StyledJsxRegistry from './styled-jsx'

import './globals.css'
import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProviders>
          <StyledJsxRegistry>{children}</StyledJsxRegistry>
        </ChakraProviders>
      </body>
    </html>
  )
}
