// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

import type { ReactNode } from 'react'

import { ReactQuery } from './providers/react-query'

import './globals.css'
import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  )
}
